version: "3.9"

services:
  mysql:
    image: mysql
    container_name: theforum-mysql
    ports:
      - "6033:3306"
    environment:
      - MYSQL_DATABASE=theforum-db
      - MYSQL_ROOT_PASSWORD=mysql
    restart: always
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
